Writable:
  LogLevel: INFO
  InsecureSecrets:
    mqtt:
      SecretName: mqtt
      SecretData:
        username: ""
        password: ""
        cacert: ""
        clientcert: ""
        clientkey: ""
Service:
  Host: 127.0.0.1
  Port: 59882
  StartupMsg: "This is the Core Command Microservice"
  RequestTimeout: 5s
Registry:
  Host: 192.168.31.32
  Port: 8500
  Type: consul
Clients:
  core-metadata:
    Protocol: http
    Host: 192.168.31.32
    Port: 59881

ExternalMQTT:
  Enabled: true
  Url: "tcp://192.168.104.90:6883"
  # ex-core-command-{DeviceName}
  ClientId: ex-core-command
  ConnectTimeout: 5s
  AutoReconnect: true
  KeepAlive: 10
  QoS: 0
  Retain: true
  SkipCertVerify: false
  SecretName: mqtt
  AuthMode: none
  Topics:
    CommandRequestTopic: edgeBox_1/edgex/command/request/#             # for subscribing to 3rd party command requests
    CommandResponseTopicPrefix: edgeBox_1/edgex/command/response       # for publishing responses back to 3rd party systems /<device-name>/<command-name>/<method> will be added to this publish topic prefix
    CommandQueryRequestTopic: edgeBox_1/edgex/commandQuery/request/#   # for subscribing to 3rd party command query request
    CommandQueryResponseTopic: edgeBox_1/edgex/commandQuery/response   # for publishing responses back to 3rd party systems
    MetadataRequestTopic: edgeBox_1/edgex/metadata/request/#   # for subscribing to 3rd party command metadata request
    MetadataResponseTopicPrefix: edgeBox_1/edgex/metadata/response   # for publishing responses back to 3rd party systems

MessageBus:
  Optional:
    ClientId: core-command
  Protocol: tcp
  Host: 192.168.31.32
  Port: 1883
  Type: mqtt
  AuthMode: none

